import type { Metadata } from 'next';
import { env, PublicEnvScript } from 'next-runtime-env';
import { Open_Sans } from 'next/font/google';
import localFont from 'next/font/local';

import { TolkitLexis } from '@/utils/lexis';

import { RootProvider } from '@/providers';

import '@/styles/global.scss';
import { generateSessionId } from '@/utils';

export const metadata: Metadata = {
  title: 'Tech Store - Next.js',
  description: 'Generated by Tech Store',
};

const open_sans = Open_Sans({
  weight: ['400', '500', '600', '700'],
  subsets: ['latin'],
});

const porto_robert = localFont({
  src: [
    {
      path: '../../public/assets/fonts/PortoRoobert-Medium.otf',
      weight: '500',
      style: 'medium',
    },
    {
      path: '../../public/assets/fonts/PortoRoobertItalic-SemiBoldItalic.otf',
      weight: '500',
      style: 'italic',
    },
    {
      path: '../../public/assets/fonts/PortoRoobert-SemiBold.otf',
      weight: '600',
      style: 'semibold',
    },
    {
      path: '../../public/assets/fonts/PortoRoobertItalic-SemiBoldItalic.otf',
      weight: '600',
      style: 'italic',
    },
    {
      path: '../../public/assets/fonts/PortoRoobert-Bold.otf',
      weight: '700',
      style: 'bold',
    },
    {
      path: '../../public/assets/fonts/PortoRoobertItalic-BoldItalic.otf',
      weight: '700',
      style: 'italic',
    },
  ],
});

const organizationID = env('NEXT_PUBLIC_ORGANIZATION_ID') || '';

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const sessionId = generateSessionId(organizationID);
  return (
    <html lang="pt-BR">
      <head>
        <PublicEnvScript />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <TolkitLexis sessionId={sessionId} organizationId={organizationID} />
      <body className={`${open_sans.className} ${porto_robert.className}`}>
        <RootProvider>{children}</RootProvider>
      </body>
    </html>
  );
}

