import type { Metadata } from 'next';
import { env } from 'next-runtime-env';

import { TolkitLexis } from '@/utils/lexis';

import { RootProvider } from '@/providers';

import '@/styles/global.scss';
import { generateSessionId, GTM } from '@/utils';
import { VWO } from '@/utils/vwo';

export const metadata: Metadata = {
  title: 'Tech Store - Next.js',
  description: 'Generated by Tech Store',
};

const organizationID = env('NEXT_PUBLIC_ORGANIZATION_ID') || '';

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const sessionId = generateSessionId(organizationID);
  return (
    <html lang="pt-BR">
      <head>
        <VWO />
        <GTM />
        <meta charSet='utf-8' />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="canonical" href="https://www.portoseguro.com.br/" />
        <title>Plano de Saúde para Pets: Ambulatorial, Essencial e Completo | Porto</title>
        <meta name="description" content="O Plano de Saúde para Pets é ideal para seu animal de estimação com os novos planos e com rede credenciada. Proteja seu pet com amor. Confira!" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <TolkitLexis sessionId={sessionId} organizationId={organizationID} />
      <body >
        <RootProvider>{children}</RootProvider>
      </body>
    </html>
  );
}

